### ISSUE TITLE
Domain Driven Design in Java EE with Reza Rahman

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/webinars#5]

**Comment by arun-gupta** [comment]
Hanginar can be joined at: https://plus.google.com/events/cs2m67lhnjhb6o7cmr3vcvaln60

It will go live a few minutes before the scheduled time (Jan 29, 10am PT).

**Comment by m-reza-rahman** [comment]
FYI, an extended version of the few slides I'll use is here: http://www.slideshare.net/reza_rahman/domain-driven-design-with-java-ee-6 (PPT downloadable). I'll not be covering many slides though and it will be mostly very conversational.

**Comment by arun-gupta** [comment]
Yep, the format is a very few slides and mostly walking through the code :-)

**Comment by arun-gupta** [comment]
http://blog.arungupta.me/domain-driven-design-javaee-hanginar5/
